#!/bin/bash
ssh root@192.168.2.$1 rm -rf /u01/apache-tomcat-7.0.91/webapps/bgecor/react/*
scp -r /Users/Eugene/Desktop/dev/s112/s112-ui/s112-ui-client/src/main/frontend/forecast/build/* root@192.168.2.$1:/u01/apache-tomcat-7.0.91/webapps/bgecor/react/